---
language: node_js

node_js:
  - "0.12"

services:
  - mongodb
  - redis-server

sudo: false

cache:
  directories:
    - node_modules
    - backend/node_modules
    - frontend/node_modules

before_install:
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install
  - "make -C ./$TIMED_ENV travis-install"

script:
  - "make -C ./$TIMED_ENV travis"

before_script:
  - "make -C ./$TIMED_ENV travis-before"

after_script:
  - "make -C ./$TIMED_ENV travis-after"

env:
  global:
    - SAUCE_USERNAME=timed
    - SAUCE_ACCESS_KEY=68af4468-3509-4254-b75f-703cbdc8795b
  matrix:
    - TIMED_ENV=backend
    - TIMED_ENV=frontend

notifications:
  email:
    - damian.senn@gmail.com
