---
language: node_js

node_js:
  - "0.12"

services:
  - mongodb
  - redis-server

sudo: false

cache:
  directories:
    - node_modules
    - frontend/node_modules
    - backend/node_modules

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install -g bower
  - npm install
  - npm install --prefix ./backend
  - npm install --prefix ./frontend
  - bower install --config.cwd=frontend

script:
  - make travis

before_script:
  - cd ./frontend
  - ember sauce:connect
  - cd ..

after_script:
  - cd ./frontend
  - ember sauce:disconnect
  - cd ..

env:
  global:
  - SAUCE_USERNAME=timed
  - SAUCE_ACCESS_KEY=68af4468-3509-4254-b75f-703cbdc8795b

notifications:
  email:
    - damian.senn@gmail.com
