---
language: node_js

node_js:
  - "4"

services:
  - mongodb
  - redis-server

sudo: false

cache:
  directories:
    - node_modules
    - backend/node_modules
    - frontend/node_modules
    - frontend/bower_components

before_install:
  - "npm config set spin false"

install:
  - npm install
  - "make -C ./$TIMED_ENV travis-install"

script:
  - "make -C ./$TIMED_ENV travis"

before_script:
  - "make -C ./$TIMED_ENV travis-before"

after_script:
  - "make -C ./$TIMED_ENV travis-after"

env:
  global:
    - CXX=g++-4.8
    - SAUCE_USERNAME=timed
    - SAUCE_ACCESS_KEY=68af4468-3509-4254-b75f-703cbdc8795b
  matrix:
    - TIMED_ENV=backend
    - TIMED_ENV=frontend

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

notifications:
  email:
    - damian.senn@gmail.com
