frontendtest:
  image: iojs
  volumes:
    - ../:/usr/src/app
  command: npm --prefix=/usr/src/app/frontend run test-docker
  environment:
    - NODE_ENV=production
    - SAUCE_USERNAME=timed
    - SAUCE_ACCESS_KEY=68af4468-3509-4254-b75f-703cbdc8795b
